version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: doctor_booking_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctor_booking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql_data:
